blah

diff --git a/.github/workflows/githubactionsbuilds.yml b/.github/workflows/githubactionsbuilds.yml
--- a/.github/workflows/githubactionsbuilds.yml
+++ b/.github/workflows/githubactionsbuilds.yml
@@ -72,34 +72,23 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
-    - name: List all files (for debugging)
-      run: ls -lah
-
-    - name: Check for files without extension
+    - name: Make executable files without extension executable
       run: |
-        echo "Listing files without extension..."
-        files=$(find . -type f ! -name "*.*")
-        if [ -z "$files" ]; then
-          echo "No files without extension found."
-        else
-          echo "Files without extension found:"
-          echo "$files"
-        fi
+        echo "Starting to process files..."
+        find . -type f ! -name "*.*" -exec sh -c '
+          for f; do
+            echo "Processing file: $f"
+            mime=$(file --mime-type "$f" | cut -d " " -f2)
+            echo "MIME type: $mime"
+            if [ "$mime" = "application/x-pie-executable" ] || [ "$mime" = "application/x-executable" ]; then
+              echo "Attempting to make $f executable"
+              chmod +x "$f" || echo "Failed to change permissions for $f"
+            else
+              echo "Skipping $f, not an executable type"
+            fi
+          done
+        ' sh {} +
 
-    - name: Debugging MIME types of files without extension
-      run: |
-        echo "Checking MIME types for files without extension..."
-        find . -type f ! -name "*.*" -exec sh -c 'for f; do echo "$f"; file --mime-type "$f"; done' sh {} +
-
-    - name: Making files without extension executable if binary or empty
-      run: |
-        echo "Attempting to make binary or empty files without extension executable..."
-        find . -type f ! -name "*.*" -exec sh -c 'for f; do file --mime-type "$f" | grep -q "x-empty\\|binary" && echo "Making $f executable" && chmod +x "$f"; done' sh {} +
-
-    - name: Verify execution permission of files without extension
-      run: |
-        echo "Verifying execution permissions for files without extension..."
-        find . -type f ! -name "*.*" -exec ls -l {} +
 
     - name: Prepare for running paq8hp12_l64
       run: |
